name: dart_application_2
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.19.0-36.0.dev <3.0.0'

dependencies:
  http: ^0.13.5

dev_dependencies:
  test: ^1.16.0
  lints: any
